Отрисуй меня полностью (часть 2)
htmlacademy-javascript/123003-keksobooking-27 pull request #6
Opened 2022-10-26 19:14 UTC by JuliaAf

2022-10-26 22:09 UTC, AlexMasterov requested changes
👍🏻

Нужно немного доработать.

2022-10-26 22:09 UTC, AlexMasterov commented on js/form.js
> +
<details>
<summary>form.js</summary>

https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/d7714e5430941ba4794b79313495e61da7269e30/js/form.js#L10
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/d7714e5430941ba4794b79313495e61da7269e30/js/form.js#L15
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/d7714e5430941ba4794b79313495e61da7269e30/js/form.js#L22
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/d7714e5430941ba4794b79313495e61da7269e30/js/form.js#L27
</details>

> Неуместное и небезопасное использование `.setAttribute` / `.removeAttribute`

Нужно во всем проекте стараться продолжать изменять DOM-элементы через типизированное (безопасное) API, используя _свойства_ самих объектов:

```diff
- field.setAttribute('disabled', true);
+ field.disabled = true;
```

> См. подробней [Документ: атрибуты и свойства](https://learn.javascript.ru/dom-attributes-and-properties)

[`Д 7`](https://up.htmlacademy.ru/javascript/27/criteries#d7)
> При использовании встроенного API, который поддерживает несколько вариантов использования, **используется один способ**

2022-10-26 22:09 UTC, AlexMasterov commented on js/form.js
> +
<details>
<summary>form.js</summary>

https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/d7714e5430941ba4794b79313495e61da7269e30/js/form.js#L13-L16
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/d7714e5430941ba4794b79313495e61da7269e30/js/form.js#L25-L28
</details>

Включение формы панели фильтров, в отличие от карты и формы объявления, зависит от нескольких условий. В одном случае её вообще не нужно будет включать.

Для работы с элементом формы панели фильтров следовало похожим образом создать отдельный модуль.


См. [`ТЗ 5.10.`](https://up.htmlacademy.ru/javascript/27/project/keksobooking#keksobooking-5-10)
> **Форма**, с помощью которой производится **фильтрация похожих объявлений**, на момент открытия страницы заблокирована и **становится доступной только после окончания загрузки всех похожих объявлений**, которые, в свою очередь, начинают загружаться **только после загрузки и успешной инициализации карты**. **Если при загрузке данных с сервера произошла ошибка запроса, то форма остаётся недоступной**

2022-10-26 22:09 UTC, AlexMasterov commented on js/main.js
> +activateForms();
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/198144736-2f6327e6-fb94-4545-b377-ed9d31064af3.png)

</details>

Можно сразу доработать в этом задание, например, добавить в разметке к полю специальный атрибут или для этого в JS использовать DOM API.

См. [`ТЗ 3.4.`](https://up.htmlacademy.ru/javascript/27/project/keksobooking#keksobooking-3-4) 
> Адрес: ручное редактирование поля запрещено

2022-10-26 22:57 UTC, AlexMasterov commented on js/form.js
> +  priceSlider.classList.add('ad-form__slider--disabled');
Из ТЗ:
> Слайдер реализуется сторонней библиотекой `noUiSlider`

Библиотека еще не используется, а уже для неё со знанием применяются специальные стили 🤔

2022-10-27 09:59 UTC, JuliaAf commented on js/form.js
> +  priceSlider.classList.add('ad-form__slider--disabled');
ТЗ в этом разделе : "Слайдер также должен быть заблокирован"
поэтому я добавила класс на контейнер для слайдера, который есть в разметке

2022-10-27 10:30 UTC, AlexMasterov commented on index.html
> +          <input id="address" name="address" type="text" disabled>
<input id="address" name="address" type="text" `disabled`>

Далее чтобы собрать все значения полей и отправить их на сервер, как данные формы, будет использоваться объект [`FormData`](https://developer.mozilla.org/ru/docs/Web/API/FormData). Проблема в том, что поле с атрибутом `disabled` в него не попадет:
```js
const formData = new FormData(document.querySelector('.ad-form'));

formData.get('address'); // null
```
Вместо `disabled` нужно использовать другой атрибут.

> Иначе придется получать значение поля адреса отдельно и вручную вставлять в данные для отправки

2022-10-27 10:30 UTC, merged

2022-10-27 10:32 UTC, JuliaAf commented on index.html
> +          <input id="address" name="address" type="text" disabled>
Вместо disabled нужно использовать другой атрибут. **readonly?**

2022-10-27 10:37 UTC, AlexMasterov commented on index.html
> +          <input id="address" name="address" type="text" disabled>
> Вместо disabled нужно использовать другой атрибут. **readonly?**

Да, попробуй с ним 😃