Помощь друга
htmlacademy-javascript/123003-keksobooking-27 pull request #9
Opened 2022-10-31 19:42 UTC by JuliaAf

2022-10-31 20:37 UTC, AlexMasterov requested changes

2022-10-31 20:37 UTC, AlexMasterov commented on js/slider.js
> +const sliderElement = document.querySelector('.ad-form__slider');
const slider`Element` = document.querySelector('.ad-form__slider');

Нужно здесь из названия убрать `Element` или добавить его в названия _всех_ переменных проекта, которые указывают на DOM-элементы (= объекты типа [`Element`](https://developer.mozilla.org/ru/docs/Web/API/Element)).

[`Д 6`](https://up.htmlacademy.ru/javascript/27/criteries#d6)
> Используется единый стиль именования переменных

> если переменные, которые хранят DOM-элемент, содержат слово `Element` или любое другое, но одно и то же везде

2022-10-31 20:37 UTC, AlexMasterov commented on js/slider.js
> +  },
<details>
<summary>slider.js</summary>

https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/7224f48e0927c0a2c9b7ae056484efe72f572172/js/slider.js#L16-L18
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/7224f48e0927c0a2c9b7ae056484efe72f572172/js/slider.js#L19-L21
</details>

`function`

[`Д 5`](https://up.htmlacademy.ru/javascript/27/criteries#d5)
> Все функции объявлены единообразно

> Для объявления методов объектов используется специальный синтаксис для методов

2022-10-31 20:37 UTC, AlexMasterov commented on js/slider.js
> +  switch(typesField.value) {
<details>
<summary>slider.js</summary>

https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/7224f48e0927c0a2c9b7ae056484efe72f572172/js/slider.js#L40
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/7224f48e0927c0a2c9b7ae056484efe72f572172/js/slider.js#L43
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/7224f48e0927c0a2c9b7ae056484efe72f572172/js/slider.js#L46
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/7224f48e0927c0a2c9b7ae056484efe72f572172/js/slider.js#L49
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/7224f48e0927c0a2c9b7ae056484efe72f572172/js/slider.js#L52
</details>

На защите в _таком_ решение _могут_ придраться к строкам с названием типа жилья.

<details>
<summary>slider.js</summary>

https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/7224f48e0927c0a2c9b7ae056484efe72f572172/js/slider.js#L41
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/7224f48e0927c0a2c9b7ae056484efe72f572172/js/slider.js#L44
</details>

Некоторые и к таким числам тоже _могут_ придраться, не смотря на контекст их использования.

[`Б 7`](https://up.htmlacademy.ru/javascript/27/criteries#b7)
> Названия констант (постоянных значений) написаны прописными (заглавными) буквами

2022-10-31 20:37 UTC, AlexMasterov commented on js/slider.js
> +  switch(typesField.value) {
<details>
<summary>slider.js</summary>

https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/7224f48e0927c0a2c9b7ae056484efe72f572172/js/slider.js#L38-L59
</details>

<details>
<summary>form.js</summary>

https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/7224f48e0927c0a2c9b7ae056484efe72f572172/js/form.js#L48-L54
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/7224f48e0927c0a2c9b7ae056484efe72f572172/js/form.js#L65-L66
</details>

Установка минимальной цены уже была реализована в прошлом задание. 

> Новый код повторно делает тоже самое, а как решение гораздо слабее прошлого

2022-10-31 20:37 UTC, AlexMasterov commented on js/slider.js
> +      min: min,
```diff
- min: min,
+ min,
```

2022-10-31 20:37 UTC, AlexMasterov commented on js/map.js
> +
<details>
<summary>map.js</summary>

https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/7224f48e0927c0a2c9b7ae056484efe72f572172/js/map.js#L31-L35
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/7224f48e0927c0a2c9b7ae056484efe72f572172/js/map.js#L37-L41
</details>

На защите _могут_ придраться.

[`Б 7`](https://up.htmlacademy.ru/javascript/27/criteries#b7) 
> Названия констант (постоянных значений) написаны прописными (заглавными) буквами.

2022-10-31 20:37 UTC, AlexMasterov commented on js/map.js
> +
<details>
<summary>map.js</summary>

https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/7224f48e0927c0a2c9b7ae056484efe72f572172/js/map.js#L20-L22
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/7224f48e0927c0a2c9b7ae056484efe72f572172/js/map.js#L45-L46
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/7224f48e0927c0a2c9b7ae056484efe72f572172/js/map.js#L77-L78
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/7224f48e0927c0a2c9b7ae056484efe72f572172/js/map.js#L81-L83
</details>

На защите _могут_ придраться.

[`Б 7`](https://up.htmlacademy.ru/javascript/27/criteries#b7) 
> Названия констант (постоянных значений) написаны прописными (заглавными) буквами

[`Д 19`](https://up.htmlacademy.ru/javascript/27/criteries#d19) 
> В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа

2022-10-31 20:37 UTC, AlexMasterov commented on js/slider.js
> +
См. ТЗ:
> **Пользователь может вписать цену в поле**, а может указать её перемещением ползунка слайдера

Если сейчас вручную ввести свою цену (или использовать стрелки) и изменить тип жилья, то цена вернется на прежние значение, которое задано с помощью слайдера.

Нужно разобраться и доработать.

2022-10-31 20:37 UTC, AlexMasterov commented on js/map.js
См. задание:
> Реализуйте с помощью API карт [выбор адреса](https://up.htmlacademy.ru/javascript/27/project/keksobooking#keksobooking-4) путём _перемещения_ главной метки

См. ТЗ:
> Значение [адреса] автоматически выставляется при _перемещении_ специальной метки по карте

Сейчас значение поля адреса с координатами изменяется _после_ перемещения, когда была отжата левая кнопка мыши.

Нужно разобраться и доработать.

2022-10-31 20:37 UTC, AlexMasterov commented on js/map.js
См. https://github.com/htmlacademy-javascript/123003-keksobooking-27/pull/6#discussion_r1006212823.

См. ТЗ:
> **Форма**, с помощью которой производится **фильтрация похожих объявлений**, на момент открытия страницы заблокирована и **становится доступной только после окончания загрузки всех похожих объявлений, которые**, в свою очередь, начинают загружаться **только после загрузки и успешной инициализации карты**. Если при загрузке данных с сервера произошла ошибка запроса, то форма остаётся недоступной

Стоит подумать и учесть в будущем.

2022-10-31 20:37 UTC, AlexMasterov commented on js/map.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/199104916-415586fe-5f49-4c4f-82ef-1a0998a06541.png)

</details>

См. ТЗ:
> При очистке [формы] (нажатие на кнопку .ad-form__reset) страница, не перезагружаясь, переходит в состояние, когда

> — фильтрация (состояние фильтров и отфильтрованные метки) сбрасывается

> — если на карте был показан балун, то он должен быть скрыт

Не учтено при реализации. Нужно доработать в этом задание.

2022-10-31 20:37 UTC, AlexMasterov commented on js/map.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/199103936-a54d26a7-6920-4ae2-ba00-1ea7c875d2e0.png)

![image](https://user-images.githubusercontent.com/700213/199104310-6e4d9176-09ab-444a-b483-e9467b2f3e55.png)

</details>

См. снова https://github.com/htmlacademy-javascript/123003-keksobooking-27/pull/7#discussion_r1008694533.

Начальное значение цены для квартиры снова отличается. 
После сброса формы цена не возвращается к исходному (который в свою очередь задан неправильно).

Нужно разобраться и снова исправить.

2022-10-31 23:49 UTC, AlexMasterov commented on js/map.js
> +  addressField.value = `${evt.target.getLatLng().lat.toFixed(5)}, ${evt.target.getLatLng().lng.toFixed(5)}`;
`${evt.target.getLatLng()`.lat.toFixed(5)}, ${`evt.target.getLatLng()`.lng.toFixed(5)

Повторное обращение к `evt.target` и вызов его метода `getLatLng()`.

См. похожие замечание https://github.com/htmlacademy-javascript/123003-keksobooking-27/pull/7#discussion_r1008733290.

2022-11-01 20:59 UTC, JuliaAf commented on js/slider.js
> +  },
тут не поняла, что нужно сделать, заменила toFixed на parseInt

2022-11-01 21:00 UTC, JuliaAf commented on js/slider.js
> +
тз выполняется, можно и вписать цену и задать ползунком. если изменить тип жилья, в слайдере выбирается минимальная цена для этого жилья, по-моему логично... не так надо?)

2022-11-01 21:00 UTC, JuliaAf commented on js/map.js
тут нужна помощь

2022-11-01 21:28 UTC, AlexMasterov commented on js/slider.js
> +
См. ТЗ:
> Под ограничением подразумевается валидация минимального значения, которое можно ввести в поле с ценой. **Изменять само значение поля не нужно**, это приведёт к плохому UX (опыту взаимодействия). Даже если уже указанное значение не попадает под новые ограничения, не стоит без ведома пользователя изменять значение поля

2022-11-01 21:40 UTC, AlexMasterov commented on js/map.js
См. ТЗ:
> Слайдер также должен быть заблокирован

Можно доработать в след. задание.

2022-11-01 21:53 UTC, AlexMasterov commented on js/map.js
См. https://github.com/htmlacademy-javascript/123003-keksobooking-27/pull/5#discussion_r1001864043 + советую внимательно посмотреть примеры с коллбэками на ретро за вчера (01.11). 

Если возникнут сложности, то лучше сразу созвониться.

2022-11-01 22:04 UTC, AlexMasterov commented on js/slider.js
> +  },
См. внимательно:
> Для объявления методов объектов используется **специальный синтаксис для методов**

См. [Определение методов](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Functions/Method_definitions).

Причина по которой я сделал это замечание необязательным в том, что разработчики спецификации из Ecma TC39 планируют изменить определение метода. По результатам их последней дискуссии подобные функции не будут считаться методами. В первую очередь, из-за отсутствия `this`, изменения значения которого вызывающей стороной не влияет на их поведение. Например, `log` в `console.log` — это уже тоже не метод 🤔

Но, нам стоит оставаться в рамках действующий спецификации и привычных определений. Исправляй на свое усмотрение или дождись замечания от случайного проверяющего 😃

2022-11-01 22:06 UTC, AlexMasterov commented on js/slider.js
> +  },
Причина по которой я сделал это замечание необязательным в том, что разработчики спецификации из Ecma TC39 планируют изменить определение метода. По результатам их последней дискуссии подобные функции не будут считаться методами. В первую очередь, из-за отсутствия `this`, изменения значения которого вызывающей стороной не влияет на их поведение. Например, `log` в `console.log` — это уже тоже не метод:

![image](https://user-images.githubusercontent.com/700213/199350892-3d4133ab-7ad9-41f0-aa82-32793942276f.png)


Но, нам стоит оставаться в рамках действующий спецификации и привычных определений. Исправляй на свое усмотрение или дождись замечания от случайного проверяющего 😃

2022-11-02 16:12 UTC, AlexMasterov requested changes

2022-11-02 16:12 UTC, AlexMasterov commented on js/filter.js
> +    select.querySelector('option:first-child').selected = true;
🤔

[`Д 23`](https://up.htmlacademy.ru/javascript/27/criteries#d23)
> Изменения применяются точечно

2022-11-02 16:12 UTC, AlexMasterov commented on js/map.js
> +
<details>
<summary>map.js</summary>

https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/6acf7cd18b187a16c2797ee50985278340f35b41/js/map.js#L11-L13
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/6acf7cd18b187a16c2797ee50985278340f35b41/js/map.js#L35-L45
</details>

[`Б 10`](https://up.htmlacademy.ru/javascript/27/criteries#b10)
> Список констант идёт перед основным кодом

2022-11-02 16:12 UTC, AlexMasterov commented on js/slider.js
> +const INITIAL_MAX_PRICE = 100000;
[`Б 10`](https://up.htmlacademy.ru/javascript/27/criteries#b10)
> Список констант идёт перед основным кодом

2022-11-02 16:12 UTC, AlexMasterov commented on js/slider.js
> +typesField.addEventListener('change', updateSlider);
typesField.addEventListener('change', `updateSlider`);

[`Д 4`](https://up.htmlacademy.ru/javascript/27/criteries#d4)
> Из названия обработчика события и функции-колбэка следует, что это обработчик

> Название обработчика строится следующим образом:

> `on` + (на каком элементе) + `что случилось`:

2022-11-04 15:19 UTC, AlexMasterov requested changes
К сожалению, нужно немного доработать.

2022-11-04 15:19 UTC, AlexMasterov commented on js/filter.js
> +  });
<details>
<summary>filter.js</summary>

https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/c50c499460fbde1bfb456abc1caee811c0870f6f/js/filter.js#L24
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/c50c499460fbde1bfb456abc1caee811c0870f6f/js/filter.js#L30
</details>

if(option.selected` === true`){ 
if(checkbox.checked` === true`){ 

[`Д 16`](https://up.htmlacademy.ru/javascript/27/criteries#d16)
> Отсутствуют лишние приведения и _проверки_ типов

2022-11-04 15:19 UTC, AlexMasterov commented on js/map.js
> +resetButton.addEventListener('click', onFormReset);
resetButton.addEventListener('click', `onFormReset`);

`resetButton` + `click` !== on`FormReset`

[`Д 4`](https://up.htmlacademy.ru/javascript/27/criteries#d4)
> Из названия обработчика события и функции-колбэка следует, что это обработчик

> Название обработчика строится следующим образом:

> `on` + (на каком элементе) + `что случилось`:

2022-11-04 15:19 UTC, AlexMasterov commented on js/slider.js
> +resetButton.addEventListener('click', onFormReset);
resetButton.addEventListener('click', `onFormReset`);

`resetButton` + `click` !== on`FormReset`

[`Д 4`](https://up.htmlacademy.ru/javascript/27/criteries#d4)
> Из названия обработчика события и функции-колбэка следует, что это обработчик

> Название обработчика строится следующим образом:

> `on` + (на каком элементе) + `что случилось`:

2022-11-04 15:19 UTC, AlexMasterov commented on js/map.js
>  };
<details>
<summary>map.js</summary>

https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/c50c499460fbde1bfb456abc1caee811c0870f6f/js/map.js#L39
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/c50c499460fbde1bfb456abc1caee811c0870f6f/js/map.js#L76
</details>

`12`

На всякий случай повторю, что на защите _могут_ придраться.

[`Д 19`](https://up.htmlacademy.ru/javascript/27/criteries#d19)
> В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа

2022-11-04 15:19 UTC, AlexMasterov commented on js/main.js
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/c50c499460fbde1bfb456abc1caee811c0870f6f/js/create-card.js#L3

```diff
- const typesEnToRu = {
+ const typeEnToRu = {
```

2022-11-04 15:19 UTC, AlexMasterov commented on js/main.js
<details>
<summary>form.js</summary>

https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/c50c499460fbde1bfb456abc1caee811c0870f6f/js/form.js#L45-L50
https://github.com/htmlacademy-javascript/123003-keksobooking-27/blob/c50c499460fbde1bfb456abc1caee811c0870f6f/js/form.js#L52-L58
</details>

`Б8`, `Д22`

См.:
https://github.com/htmlacademy-javascript/123003-keksobooking-27/pull/5#discussion_r1001727740
https://github.com/htmlacademy-javascript/123003-keksobooking-27/pull/7#discussion_r1008734496

2022-11-04 15:19 UTC, AlexMasterov commented on js/slider.js
> +export { initSlider, slider };
export { initSlider, `slider` };

Нужно экспортировать не элемент, а функцию, которая с ним работает, например, `resetSlider`.

> См. [Сокрытие](https://ru.wikipedia.org/wiki/%D0%A1%D0%BE%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)) и [Инкапсуляция](https://ru.wikipedia.org/wiki/%D0%98%D0%BD%D0%BA%D0%B0%D0%BF%D1%81%D1%83%D0%BB%D1%8F%D1%86%D0%B8%D1%8F_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5))

2022-11-04 16:15 UTC, AlexMasterov commented
👍🏻

2022-11-04 16:33 UTC, merged